### PR TITLE
`README.md`: Update/Strip upstream data

### PR DESCRIPTION
**Pull request by stdedos**

### CODE REVIEW

**Review by pavankjadda — APPROVED** [review]

**Comment by stdedos** [comment]
btw v2.1.0 does not work. It is installable, yes, but the "default folding" of top-level Excluded directories does not work. I've checked already the Project config, and the plugin's settings - all appear good

**Comment by pavankjadda** [comment]
> btw v2.1.0 does not work. It is installable, yes, but the "default folding" of top-level Excluded directories does not work. I've checked already the Project config, and the plugin's settings - all appear good

try version 2.2.0

**Comment by stdedos** [comment]
Still doesn't 😅

**Comment by RuslanSafa** [comment]
> Still doesn't 😅

there is also nothing that does not work on 2.1.0 and 2.2.0

**Pull request closed without merging**
